"""Added Access Token to User

Revision ID: a68a9e451171
Revises: ad16b2e2a3e3
Create Date: 2023-09-07 21:55:39.960010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68a9e451171'
down_revision: Union[str, None] = 'ad16b2e2a3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessToken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accessToken')
    # ### end Alembic commands ###
