"""Create User Table

Revision ID: ad16b2e2a3e3
Revises: 4ad080f3e5a0
Create Date: 2023-08-30 23:18:43.328557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad16b2e2a3e3'
down_revision: Union[str, None] = '4ad080f3e5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('areas_of_interest', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.drop_column('users', 'age')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'areas_of_interest')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
